DROP DATABASE IF EXISTS user;
DROP DATABASE IF EXISTS contact;
DROP DATABASE IF EXISTS offline_msg;

CREATE DATABASE IF NOT EXISTS user DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS contact DEFAULT CHARACTER SET utf8;
CREATE DATABASE IF NOT EXISTS offline_msg DEFAULT CHARACTER SET utf8;
