DROP TABLE IF EXISTS user.user;

CREATE TABLE IF NOT EXISTS user.user (
	uin INT UNSIGNED NOT NULL AUTO_INCREMENT,
	nick VARCHAR(32) NOT NULL,
	password CHAR(16) NOT NULL,
	contact_table TINYINT UNSIGNED NOT NULL DEFAULT 0,
	rsv_1 VARCHAR(32) NULL,
	rsv_2 VARCHAR(32) NULL,
	rsv_3 VARCHAR(32) NULL,
	rsv_4 VARCHAR(32) NULL,
	PRIMARY KEY (uin),
	UNIQUE INDEX uin_UNIQUE (uin ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 100;

GRANT ALL ON user.user TO root;
GRANT ALL ON user.user TO im_root;
GRANT SELECT, UPDATE, INSERT, DELETE ON user.user TO im_user;
